// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJkAkrAhUlDhu7rU5RxoQlIZ1Y5p2sA8',
    appId: '1:101997307881:web:a2e6b9dd23b4e0d5844d78',
    messagingSenderId: '101997307881',
    projectId: 'swiftmart-9',
    authDomain: 'swiftmart-9.firebaseapp.com',
    storageBucket: 'swiftmart-9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIIORdxthu-z7Pzu7Qu39YBDjJjH2LnAc',
    appId: '1:101997307881:android:1c8e0130ad80b3ed844d78',
    messagingSenderId: '101997307881',
    projectId: 'swiftmart-9',
    storageBucket: 'swiftmart-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4mg_grNOqIbH4fIefKQdpHrD2DEZVDI',
    appId: '1:101997307881:ios:264c1797d9c24ffb844d78',
    messagingSenderId: '101997307881',
    projectId: 'swiftmart-9',
    storageBucket: 'swiftmart-9.firebasestorage.app',
    iosClientId: '101997307881-mgcvla30ooffbej14uh193p6j7siuiic.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4mg_grNOqIbH4fIefKQdpHrD2DEZVDI',
    appId: '1:101997307881:ios:264c1797d9c24ffb844d78',
    messagingSenderId: '101997307881',
    projectId: 'swiftmart-9',
    storageBucket: 'swiftmart-9.firebasestorage.app',
    iosClientId: '101997307881-mgcvla30ooffbej14uh193p6j7siuiic.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHJkAkrAhUlDhu7rU5RxoQlIZ1Y5p2sA8',
    appId: '1:101997307881:web:2c2d94af81e1e66e844d78',
    messagingSenderId: '101997307881',
    projectId: 'swiftmart-9',
    authDomain: 'swiftmart-9.firebaseapp.com',
    storageBucket: 'swiftmart-9.firebasestorage.app',
  );
}
